name: Check Metadata Ownership

on:
  pull_request:
    branches: [main]

jobs:
  ownership-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run ownership check and capture output
        id: ownership
        run: |
          set +e
          output=$(python scripts/check_ownership.py)
          exit_code=$?
          echo "$output"
          echo "ownership_output<<EOF" >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          exit $exit_code

      - name: Comment on PR if ownership is missing
        if: failure()  # Only run this step if the previous one failed
        uses: actions/github-script@v6
        with:
          script: |
            const body = `${{ steps.ownership.outputs.ownership_output }}`;
            if (body.includes('"owner": "team-???"')) {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `🚨 **Missing Ownership Detected**\n\nPlease add the following entries to \`ownership/OWNERS.json\`:\n\n\`\`\`json\n${body.trim()}\n\`\`\`\nReplace \`team-???\` with the appropriate owner.`
              });
            }